name: Publish release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: make link-dependencies

      - name: Build
        run: make release

      - name: Publish release
        uses: ghalactic/github-release-from-tag@v6
        with:
          reactions: hooray,heart,rocket
          assets: |
            - path: artifacts/branding.zip
              name: ghalactic.branding.zip
              label: Ghalactic branding assets
